### ISSUE TITLE
WIN: Instant crash of Stata

### ISSUE THREAD

**Issue by heidenfahrt** [mcaceresb/stata-gtools#1]
When running a `gcollapse` or `gegen` command, Stata directly quits with a Windows Error Message. I't in German but maybe it helps anyhow.
Problemereignisname:	APPCRASH
  Anwendungsname:	StataMP-64.exe
  Anwendungsversion:	521.13.1.222
  Anwendungszeitstempel:	5567795b
  Fehlermodulname:	env_set_windows.plugin
  Fehlermodulversion:	0.0.0.0
  Fehlermodulzeitstempel:	5946e14a
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	0000000000001505
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	86b5
  Zusatzinformation 2:	86b57a8af37a99527b6b1746d2e86099
  Zusatzinformation 3:	41fb
  Zusatzinformation 4:	41fb44b28c1de6cadb0770927f4e2baf

**Comment by mcaceresb** [comment]
Windows version?

**Comment by heidenfahrt** [comment]
Win 7, 64 bit

**Comment by sergiocorreia** [comment]
Just as a follow-up, it's the same issue I have (on Win10), and I think that besides the usual suspect (memory allocation issue) it could be a recursive call problem (infinite recursion).

Using VerySleepy (something like valgrind), I can see this stack of functions being called (in that order):

- CIMEUIWindowHandler::ImeUIWndProcWorker	8.19s	98.36%	MSCTF
- ImmUnlockIMC	8.19s	100.00%	IMM32
- LocalUnlock	8.19s	100.00%	KERNELBASE
- RtlUnlockHeap	8.19s	100.00%	ntdll
- [000A735C73756C70]	8.19s	100.00%	ntdll
- (many child calls with random strings as the one above)

**Comment by mcaceresb** [comment]
@heidenfahrt : Could you help me with the debugging? (It would be best if you did the 3rd step last.)

1. Please run the following from an interactive stata Stata session and let me know if it crashes:
```
program env_set, plugin using("env_set_windows.plugin")
local path: env PATH
if inlist(substr(`"`path'"', length(`"`path'"'), 1), ";") {
    local path = substr("`path'"', 1, length(`"`path'"') - 1)
}
plugin call env_set, PATH `"`path';`c(pwd)'"'
```

2. Please do the following:
- Press "Windows Key" + "r"
- Type "cmd"
- Press "Enter"
- Then type the following
```batch
echo %PATH%
SET PATH=C:\;%PATH%
echo %PATH%
```

I don't need the output; you should get a list of ";"-delimited file paths the first time and the same list with "C:\" prepended the second time. I just want to know if that was indeed the output or if you got an error along the way.

3. Please upgrade to gtools-0.6.5 in the develop branch (just committed):
```stata
net uninstall gtools
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
```

Now make sure that [spookyhash.dll](https://github.com/mcaceresb/stata-gtools/blob/develop/build/spookyhash.dll) is in your working directory. Run any `gcollapse` or `gegen` command and let me know if they crash.

I doubt this is related to the problem @sergiocorreia was having, which has to do with memory allocation. Either way, however, that issue shouldn't cause a crash anymore---as of this version the program will exit with error when the OS runs out of memory.

**Comment by sergiocorreia** [comment]
BTW, on my laptop (where I couldn't get it to run on the first place) the new version still crashes immediately after running step 1.

So it might be two issues, a memory issue on the desktop (which for some reason works for small datasets), and an unknown issue on the laptop. Laptop has Win10 Home with 8gb, Desktop Win10 Enterp. with 24gb.

**Comment by heidenfahrt** [comment]
@mcaceresb Thank you for the quick support.
Running step 1 still crashes Stata directly.
Running step 2 leads to the desired output in the cmd window. (Should one remove C:\ from PATH?)
Running step 3 leads to a crash when running a command but the spookyhash.dll was not in my working directory. **After manually downloading and saving spookyhash.dll to the working directory, `gegen` and `gcollapse` work as desired.**

**Comment by mcaceresb** [comment]
@sergiocorreia: Running out of memory shouldn't be cause a crash in the latest version in the "develop" branch (currently gtools-0.6.7). At least in testing, it mimics Stata's behavior when it runs out of memory and simply gives an error. (Note, however, that while Windows is trying to use the pagefile Stata will not be responsive until it is either successful or it runs out of memory and gives an error; you can monitor this by monitoring disk activity).

@heidenfahrt: The problem is that on Windows I was unable to include the SpookyHash library in the Stata plugin. The workaround I use is to add the path to spookyhash.dll to the system's path before each run. However, it seems that this causes a crash on some systems (this also appears to be the problem @sergiocorreia was having earlier). Can you upgrade to `gtools-0.6.7` in the develop branch and try again? Run:

```stata
net uninstall gtools
net install gtools, from(https://raw.githubusercontent.com/mcaceresb/stata-gtools/develop/build/)
program env_set, plugin using("env_set_windows.plugin")
plugin call env_set, PATH
local path: env PATH
if inlist(substr(`"`path'"', length(`"`path'"'), 1), ";") {
    local path = substr("`path'"', 1, length(`"`path'"') - 1)
}
plugin call env_set, PATH `"`path';`c(pwd)'"'
```

Let me know for both calls to `env_set` the last message printed on the console. The first call should not cause a crash; it should just exit with error code 198. The second might cause a crash, but I'm hoping it won't...

(By the way, setting environment variables via SET should only apply to the current session. If you open another terminal and type `echo %PATH` it should not contain "C:\". To set it permanently you have to use `SETX /M`.)

**Comment by heidenfahrt** [comment]
The first call indeed results in error 198:
`
debug-1
env_set: incorrect number of arguments (1). Use:
        plugin call env_set, ENV `"VALUE"'
r(198);
`
The second call still crashes Stata.

**Comment by sergiocorreia** [comment]
> @heidenfahrt: The problem is that on Windows I was unable to include the SpookyHash library in the Stata plugin. The workaround I use is to add the path to spookyhash.dll to the system's path before each run. However, it seems that this causes a crash on some systems (this also appears to be the problem ..

For some reason I can find it on the laptop:

```
. findfile spookyhash.dll
c:\ado\plus/s/spookyhash.dll
```

Latest version still crashing btw =/

**Comment by mcaceresb** [comment]
@sergiocorreia: You mean set_env or the out-of-memory crash? For set_env, the problem is not whether Stata can find the file, but whether when Stata loads the C plugins it can tell the C plugin where the file is. It appears Stata does not do that, so I have to add the file's location to the system's path myself.

@heidenfahrt: Thanks for trying that out. I will continue to try and debug; I have yet been able to reproduce, so I think I need to find a windows machine where Stata also crashes for me. If you want to try out the function, a temporary workaround is to run
```stata
findfile spookyhash.dll
```

And append the resulting path to your system's path (Control Panel > Ctrl + F > Environment Variables > Edit the System's Environment Variables > Advanced > Environment Variables... > Path > Edit... > New; alternatively, from a terminal run `SETX /M C:\ado\plus\s\spookyhash.dll;%PATH%`). It feel that's a bit of a hassle, which is why I tried to provide the set_env function to do it automatically.

**Comment by sergiocorreia** [comment]
`set_env` works fine, but whenever I try to run the plugin I just get a crash.  Interesting about the location...

**Comment by mcaceresb** [comment]
@sergiocorreia: I see. Then I think it must be a different issue, then. Their error message stated "Fault module name: env_set_windows.plugin"; if you run with the options `verbose benchmark` does it print anything to the console or does it crash right away?

**Comment by heidenfahrt** [comment]
My machine does not recognize `findfile` as a valid command.
I cannot change the system, only the user path as I'm not admin. This seems not to be enough. Might that be the issue anyhow?

**Comment by mcaceresb** [comment]
@heidenfahrt: I tried it from a non-admin account and env_set ran for me, so it might be another issue. As for "findfile", did you run that from Stata? Try `which findfile` from the Stata console.

**Comment by heidenfahrt** [comment]
Sorry, now I got it. It yields the same path Sergio's:
`findfile spookyhash.dll
c:\ado\plus/s/spookyhash.dll`

**Comment by sergiocorreia** [comment]
By the way, I found the cause of the crash on my laptop. If the PATH is too long, the plugin crashes. My guess is that somewhere there is a maximum length assigned for the PATH. In the case of my laptop, PATH has 2000+ characters, so it crashes.

More specifically, if PATH is up to 1016 chars it works, if it is 1017 it starts and endless loop (maybe due to 0-ending of strings), and if it is 1018 or more it crashes.

**Comment by sergiocorreia** [comment]
Also, I'm not sure why we need to pass the entire $PATH. Is it so the plugin can call spookyhash DLLs located in other places?

**Comment by sergiocorreia** [comment]
Update: I got it to run after modifying the two occurrences of this line:

```stata
cap plugin call env_set, PATH `"`path';`__gtools_hashpath'"'
````

Into this:

```stata
cap plugin call env_set, PATH `"`__gtools_hashpath'"'
```

**Comment by mcaceresb** [comment]
Thanks! I was able to reproduce the crash and I know what the culprit is. I should have a fix in the master branch this afternoon.

**Comment by heidenfahrt** [comment]
Awesome. Thanks a lot for your work. Your code (and also Sergios) are making Stata life a lot easier.
