### ISSUE TITLE
Possible issues with equal signs in locals

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#3]
This mostly applies for older versions of Stata (e.g. Stata 12), but in general it's risky to have lines such as

```stata
local xyz = substr(..)
```

Because the equal sign truncates the local. A good explanation of why is here: http://www.stata-journal.com/sjpdf.html?articlenum=pr0045

**Comment by mcaceresb** [comment]
I have no way of checking, since I don't have older Stata versions, but if I just to the extended macro `substr`, will that fix any potential issues? I would assume so, since the solution there is to use extended macro functions, but I can't actually check. I mean, on my machine `substr` handled a string with 10,000 characters just fine.

I generally prefer to have the right hand evaluate so this is very much intentional, but I hadn't realized older versions might have an issue with it.

**Comment by sergiocorreia** [comment]
That's correct, replacing all cases of `local ... =` with their extended macro counterparts will fix the issue. That's something I had to do for reghdfe after a few bug reports:

https://github.com/sergiocorreia/reghdfe/commit/7c87214535bbe5ea9a7cdddd525ca647ba27726d

That said, my advice would be to leave it in the backburner. Much more useful would be MP support for Windows, OSX support, etc., as the overlap between Stata 12 and `gtools` is probably low.

**Comment by mcaceresb** [comment]
Sure, but it's also low-hanging fruit. I am also working on multi-threaded support for Windows but it's proving a bit tricky. As for OSX, a port is on hold until I can get someone to compile on Apple hardware for me. I tried and failed to set up a virtual machine with OSX, so I don't have an ETA for that anymore.

**Comment by mcaceresb** [comment]
This should be fixed in version `0.6.10`- (master branch).
