### ISSUE TITLE
Error message for all commands with Stata MP 15.1

### ISSUE THREAD

**Issue by benwaltmann** [mcaceresb/stata-gtools#59]
No commands seem to work with gtools under Stata MP/15.1 but everything works fine with Stata MP/14.2 .  (Another difference is that the Stata MP/15.1 machine is in a secure environment without direct accesss to the internet, but I wouldn't have thought that mattered.) Minimal example:

. gtools
Nothing to do. See help gtools or gtools, examples for usage. Version info:
c:\ado\plus\g\gtools.ado
*! version 1.5.1 24Mar2019 Mauricio Caceres Bravo, mauricio.caceres.bravo@gmail.com
*! Program for managing the gtools package installation
class GtoolsResults undefined
(282 lines skipped)
(error occurred while loading _gtools_internal.ado)
(warning: gtools_plugin internal check failed)
.

**Version info**
 - OS: Windows Server 2008 R2 Enterprise
 - Version:  1.5.1 24Mar2019

**Comment by mcaceresb** [comment]
I think that your install is missing `lgtools.mlib`. What happens if you do

```
which lgtools.mlib
findfile lgtools.mlib
mata mata mlib query
```

Can you walk me through how you installed `gtools` if you don't have access to the internet?

**Comment by benwaltmann** [comment]
Thank you very much for the quick reply. Below are the outputs of these commands. The precise processes are a bit of a black box to me (could ask, though), but my understanding is that the system administrator is able to access the internet from the machine and thus can just run  

```
ssc install gtools
gtools, upgrade
```

```
. which lgtools.mlib
c:\ado\plus\l\lgtools.mlib
. findfile lgtools.mlib
c:\ado\plus/l/lgtools.mlib
. mata mata mlib query
.mlib libraries to be searched are
lmatabase;lmataado;lmataerm;lmatafc;lmatagsem;lmatamcmc;lmatamixlog;lmataopt;lmatapath;lmatapostest;lmatapss;lmatasem;lmatasvy;lmatatab;lmoremata;lmoremata10;lmoremata14;l_cfrmt

```

(apologies for typos -- can't copy and paste from secure environment)

**Comment by mcaceresb** [comment]
Maybe try

```
mata: mata mlib index
```

?

**Comment by sergiocorreia** [comment]
Hi Mauricio!

In case it's useful, a constant pain point I had with users in ftools and reghdfe involved missing `.mlib` files, or mlib files build using older versions of Stata (or reghdfe) that users can't update because of system permissions.

Another problem is that the first time an mlib file gets loaded (either after Starting stata, or running "clear all"), the library takes up to a few seconds to load, which is not ideal.

After a lot of iterations, the solution that best worked for me is just to include a `.mata` file at the end of each ado, like here:

https://github.com/sergiocorreia/reghdfe/blob/master/src/reghdfe.ado#L529

**Comment by benwaltmann** [comment]
Thanks very much! Just restarting Stata was enough (sorry for being slow). Thank you Mauricio and Sergio for writing great software.
