### ISSUE TITLE
gegen std() function?

### ISSUE THREAD

**Issue by sergiocorreia** [mcaceresb/stata-gtools#62]
Hi Mauricio,

I just noticed that it might be useful to have something like egen's `std` function to standardize variables. It would be equivalent to combining the already implemented mean() and sd() functions, but with a speedup (as data would only be shuffled once, and factors would only be computed once).

Note though that egen's std() does not support by() (so its not very useful). Also, the mean() and sd() options of std() don't seem very useful so you might not even care about implementing them.

Best,
S

**Comment by mcaceresb** [comment]
What does std do?

**Comment by sergiocorreia** [comment]
It's equivalent to:

```stata
	gegen sd = sd(y), by(id)
	gegen mean = mean(y), by(id)
	gen standardized= (y - mean) / sd
```

So it just turns `y` into a variable with mean zero and standard deviation of 1 (within `by`)

**Comment by mcaceresb** [comment]
oh, sure. I'll add it.

**Comment by mcaceresb** [comment]
I added a command to do this. Feel free to try out in `develop`. The functions are called standardize/normalize and demean, available for `gegen` and for `gstats transform` (the latter is a new command with identical syntax to gcollapse but all the functions are meant to be at the ij level rather than j level). You can pass option `nogreedy` which is slower but has a relatively lean memory footprint.

I think I'll eventually add some other functions (like lag, lead, moving average, rolling stats, etc.) but I think this is enough for now. (PS: I also allow `winsor` and `xtile` as aliases to `gegen` in case you want to use it like that).

**Comment by mcaceresb** [comment]
i added moving statistics (moving average, moving standard deviation etc.). I think the next step is to allow using intervals, similar to "rangestat". This would allow "rolling" statistics in the style of rolling, tsgen, etc. It's a bit of work so I'll leave it like this for now.

**Comment by mcaceresb** [comment]
I also added interval statistics, which covers some of the functionality of rangestat (only summary stats though, no reg). It can also set the bounds to be a summary stat, which I though was pretty cool:

```stata
webuse grunfeld, clear

local s1 (mean -3 3 year)   x1 = invest
local s2 (median -2 . year) x2 = invest
local s3 (p33.3 . 1 year)   x3 = invest
local s4 (sum -sd  sd)      x4 = invest
local s5 (count -0.5cv 2.7p66.6 mvalue)  x5 = invest

gstats range `s1' `s2' `s3' `s4' `s5', by(company)
```
