### ISSUE TITLE
estpost support for gtabstat

### ISSUE THREAD

**Issue by laszlosandor** [mcaceresb/stata-gtools#65]
`tabstat` is often used to produce output directly, with `estpost tabstat`. As much as `gtabstat` replaces `tabstat`, it would be great to use it as `estpost gtabstat`.

http://repec.org/bocode/e/estout/hlp_estpost.html#tabstat

**Comment by mcaceresb** [comment]
Interesting. I guess I can submit a pull request to [benhann/estout](https://github.com/benjann/estout) to add `gstats tabstat` support to estout.

It'll take a bit because the estpost code looks somewhat convoluted (I don't think it's his fault; tabstat returns the summary stats in an awkward way).

**Comment by mcaceresb** [comment]
@laszlosandor Made a PR. See: https://github.com/benjann/estout/pull/21

**Comment by mcaceresb** [comment]
The PR was merged to master.
