### ISSUE TITLE
use frames in Stata 16

### ISSUE THREAD

**Issue by laszlosandor** [mcaceresb/stata-gtools#66]
Stating the obvious: we should do away with the preserve-restore cycle whenever we can. In many big data projects, that was the bottleneck. I once rewrote `binscatter` just to avoid it. So, celebrate and spread the word: [Stata can finally hold multiple datasets in memory](https://www.stata.com/new-in-stata/multiple-datasets-in-memory/).

**Comment by mcaceresb** [comment]
Well, it's not just the preserve/restore thing. The _entirety_ of gcollapse bends over backwards because Stata can't hold multiple datasets in memory. I have a section in the docs about it. The `frame` command sounds interesting and long overdue.

Anyway, I don't have Stata 16 (though I probably will eventually).

**Comment by laszlosandor** [comment]
Well, but you still do a `preserve`, no? Now you can do away with even that. I understood that the C plugin was necessary partly because of this limitation.

Tell Mike you need version 16 and everything will be covered in fairy dust!

**Comment by mcaceresb** [comment]
Actually, now that i am thinking about it, it might be a lesser re-write than I thought if I don't have _access_ to the other datasets in memory from C, which I might not. Ah, well.

In any case, I can change the -fast- option to a memory-based option (so I will still avoid frames to preserve memory, if that is a concern). I don't know who Mike is.

**Comment by laszlosandor** [comment]
Sorry, Professor Sinkinson, then. He is an old friend.

**Comment by mcaceresb** [comment]
Ah, yes, I do know Professor Sinkinson, but this is actually my last week at Yale. Some timing.

**Comment by sergiocorreia** [comment]
Chiming in:

I thought Stata 16 rewrote preserve/restore to use frames internally, so no rewrite is required:

"The do- and ado-files that you have previously written that use preserve and restore will run faster if you use Stata/MP because it secretly uses frames in place of temporary files to preserve data",
https://www.stata.com/new-in-stata/multiple-datasets-in-memory/

**Comment by laszlosandor** [comment]
Ah, reading has always been my strong suit. Thanks, @sergiocorreia !

**Comment by mcaceresb** [comment]
Well, I'm on the "not everyone has Stata/MP" train and forever annoyed at some of the non-MP limitations. Like this one. Limiting cores? Sure. But this is will prompt me to have code in place using frames to account for IC and SE when I otherwise could have done nothing, no?

**Comment by sergiocorreia** [comment]
Agreed. Surprised they excluded SE here.

**Comment by mcaceresb** [comment]
I have been using frames in Stata for some time now. While there are probably many places where it might make sense to use frames, I do not think the speed improvement will be first order because the plugin interface can only interact with the frame that is currently in memory, and there is  no way to change frames from C. I might revisit in the future but closing this for now.
