### ISSUE TITLE
gegen normalize does not realize that a new variable shall be created

### ISSUE THREAD

**Issue by felixholub** [mcaceresb/stata-gtools#74]
**Describe the bug**
When using `gegen` with `normalize`, a target exists error is returned if a variable beginning with the same name exists.
With `mean`, for example, this does not happen.

**Code Sample**
```stata
sysuse auto, clear

// works fine with mean
gegen mpg_aa = mean(mpg)
gegen mpg_a = mean(mpg)

// does not work with normalize
gegen mpg_bb = normalize(mpg)
// throws arrow as it thinks that mpg_b refers to mpg_bb
gegen mpg_b = normalize(mpg), verbose bench(3)
```

```stata


. sysuse auto, clear
(1978 Automobile Data)

. // works fine with mean
. gegen mpg_aa = mean(mpg)
. gegen mpg_a = mean(mpg)

. // does not work with normalize
. gegen mpg_bb = normalize(mpg)

. // throws arrow as it thinks that mpg_b refers to mpg_bb
. gegen mpg_b = normalize(mpg), verbose bench(3)
Parsed by variables; .002 seconds
gstats_transform: target mpg_b exists without replace
r(198);
```

**Version info**
 - OS: Windows 10
 - Version: 1.7.5

**Comment by mcaceresb** [comment]
@felixholub As a quick fix, add `set varabbrev off`

I legitimately cannot remember what issues `varabbrev` caused that effected me to  comment out [this line](https://github.com/mcaceresb/stata-gtools/blob/master/src/ado/_gtools_internal.ado#L84). I am personally very strongly against `varabbrev` but have had to deal with it somewhat since Stata has it turned on by default.

I _believe_ the fix is to change the way I check for whether a variable exists from a failure of `confirm var` to a success of `confirm new var`, but won't have time to test it for a bit.
