### ISSUE TITLE
gtools 1.8.1 not working *at all* with Stata MP 16.1 on MacOS 11.6

### ISSUE THREAD

**Issue by effedp** [mcaceresb/stata-gtools#80]
As from the title, upgrading to version 1.8.1 _completely_ shuts off any command related with gtools.

Even a super-basic setting as the one which follows, where I try three different gtools commands, raises the same error.

With a brand new installation with ```ssc install gtools, replace```—which installs the 1.5.1 version—everything works fine.

**Code Sample**
```stata
clear all

set obs 1000
gen p = _n

hashsort p, verbose bench(3)

gegen m = max(p), verbose bench(3)

gstats tabstat p, s(mean) verbose bench(3)
```

For each command, the same error:
```stata
. hashsort p, verbose bench(3)
Parsed by variables; .023 seconds
r(111);

. gegen m = max(p), verbose bench(3)
Plugin setup; .025 seconds
Parsed by variables; .004 seconds
r(111);


. gstats tabstat p, s(mean) verbose bench(3)
Parsed by variables; .005 seconds
r(111);
```

I am using **Stata MP 16.1** on **MacOS 11.6**.

Thank you for your help and time.

**Comment by mcaceresb** [comment]
@effedp Please run`gtools` on a fresh Stata session. If there is no error, then please post the log file of the comments you executed above with `set trace on` executed right before.

**Comment by effedp** [comment]
Hi Mauricio,

same error even with a fresh Stata session.

Please find attached the log file.
Notice that I had to run the three commands above with ```cap``` before to let Stata execute all the three of them without stopping.

[gtools_181.log](https://github.com/mcaceresb/stata-gtools/files/7250562/gtools_181.log)

**Comment by tmalthouse** [comment]
I'm observing the same problem—gtools 1.8.1, Stata 16.0, MacOS 10.14.6. Running any  gtools command (I've checked gegen, gcollapse, and gstats transform range so far) gives r(111); without any further information.

Happy to provide log files or more details if they'd be useful.

**Comment by mcaceresb** [comment]
@effedp @tmalthouse This does sound like a bug. I suspect the issue is that the OSX plugin version is for some reason stuck at 1.7.5 instead of 1.8.1 as it should be (you can see the discrepancy [here](https://github.com/mcaceresb/stata-gtools/issues/80#issuecomment-929998812)). I rely on Travis to compile the OSX plugin and they recently changed the way their site works, so that might have messed things up. I will have a closer look later in the week.

In the meantime, if you follow the steps [here](https://github.com/mcaceresb/stata-gtools/issues/73#issuecomment-803444445) it should fix your issue.

**Comment by tmalthouse** [comment]
Building it locally worked perfectly—thank you!

**Comment by effedp** [comment]
I confirm that local building works for me too. Thank you Mauricio.

**Comment by mcaceresb** [comment]
Solution [here](https://github.com/mcaceresb/stata-gtools/issues/80#issuecomment-930351652).
