### ISSUE TITLE
Could not load gtools_macosx_v3.plugin, error 9999

### ISSUE THREAD

**Issue by austinsmoss** [mcaceresb/stata-gtools#87]
I am having the same issue described in issue #73 (same issue title) even though that report mentions that the issue should be fixed in the updated gtools version. The fix described in that thread by @florianpeters does work, but I wanted to bring it to your attention that the issue is still (again?) outstanding.

I am running Stata 17.0 on a 2021 Macbook Pro with M1 Pro chip.

**Comment by mcaceresb** [comment]
@austinsmoss I am kind of aware since someone commented they still had the problem but unfortunately I'm not 100% what to do about it. I should at least make a note of it somewhere, though, so I'll leave this issue open this time. Thankfully compiling on OSX is not too bad; I believe [this comment](https://github.com/mcaceresb/stata-gtools/issues/73#issuecomment-877666362) compiles and clarifies the instructions I gave throughout the thread. I repeat here for convenience:

1. Build gtools. From the command line (terminal)

```
git clone https://github.com/mcaceresb/stata-gtools
cd stata-gtools
git submodule update --init --recursive
make clean SPI=3.0 SPIVER=v3
make all   SPI=3.0 SPIVER=v3
```

2. Uninstall gtools, if a previous version was present. From Stata,


```
ssc uninstall gtools
net uninstall gtools
```

3. Install from local folder. From Stata,

```
net install gtools, from(/path_to_folder_where_gtools_was_compiled/stata-gtools/build) replace
```

Anyway, the issue is that there was some change either in OSX or with the Apple processors that broke the plugin and since I don't have a mac, I can't debug the issue. I thought compiling with github would help but apparently it's still broken on some systems. I suppose even if I did have a Mac, I don't really know whether my fix would break comparability with older models or OSX versions. There's a similar issue on some Windows servers, if I recall, that is still open (#60) and I don't have Windows hardware, let alone a Windows server.

**Comment by mcaceresb** [comment]
@austinsmoss Can you share your OS version?

**Comment by austinsmoss** [comment]
Monterey v 12.5

**Comment by mcaceresb** [comment]
@austinsmoss If you try to use the original plugin (the one that failed), after you have done so, do you see under " System Preferences > Security & Privacy > General" a note that macOS has blocked the plugin and to allow it to run anyway?

**Comment by austinsmoss** [comment]
I do not see this option. Would it be useful to Zoom so I can share my screen? If so, shoot me an email at austin.moss@colorado.edu

**Comment by mcaceresb** [comment]
@austinsmoss I am asking because a user of a different plugin recently had this issue after upgrading to the latest macOS, where the system gave the message that the execution of the plugin had been blocked. The solution is for me to sign it (costs $ apparently), for the user to unblock it (in Security and Privacy, hence my question), or for the user to compile (which is what this thread suggests, but I figured unblocking it might be easier).

I do not own a mac, and it's been several years since I used one, so I am not sure if I'd be that helpful even with screen share. I am basing my question off a google search, actually Un_n. Just to be sure, though, you checked after trying to use the plugin file that caused gtools to _fail_, yes?

**Comment by austinsmoss** [comment]
Understood. Yes, I uninstalled the working version that I compiled and reinstalled the SSC version. I am not given that error message.

**Comment by chisquared** [comment]
To confirm, the instructions in [the comment above](https://github.com/mcaceresb/stata-gtools/issues/87#issuecomment-1196870571) worked perfectly for me on a M1 Macbook Pro, running macOS 12.5.1. 

I couldn't run `ssc uninstall gtools`, which gave the error `criterion matches more than one package`. But just reinstalling with `net install gtools, from($folder/stata-gtools/build) replace` worked regardless of the existing package, and got the plugin working. 

I didn't see any warnings in System Preferences > Security about the plugin being blocked, so I suspect it is just that the Mac is looking for the plugin to be compiled as ARM, and doesn't know to run the Intel plugin with Rosetta emulation.

**Comment by annorazhao** [comment]
> @austinsmoss I am kind of aware since someone commented they still had the problem but unfortunately I'm not 100% what to do about it. I should at least make a note of it somewhere, though, so I'll leave this issue open this time. Thankfully compiling on OSX is not too bad; I believe [this comment](https://github.com/mcaceresb/stata-gtools/issues/73#issuecomment-877666362) compiles and clarifies the instructions I gave throughout the thread. I repeat here for convenience:
> 
> 1. Build gtools. From the command line (terminal)
> 
> ```
> git clone https://github.com/mcaceresb/stata-gtools
> cd stata-gtools
> git submodule update --init --recursive
> make clean SPI=3.0 SPIVER=v3
> make all   SPI=3.0 SPIVER=v3
> ```
> 
> 2. Uninstall gtools, if a previous version was present. From Stata,
> 
> ```
> ssc uninstall gtools
> net uninstall gtools
> ```
> 
> 3. Install from local folder. From Stata,
> 
> ```
> net install gtools, from(/path_to_folder_where_gtools_was_compiled/stata-gtools/build) replace
> ```
> 
> Anyway, the issue is that there was some change either in OSX or with the Apple processors that broke the plugin and since I don't have a mac, I can't debug the issue. I thought compiling with github would help but apparently it's still broken on some systems. I suppose even if I did have a Mac, I don't really know whether my fix would break comparability with older models or OSX versions. There's a similar issue on some Windows servers, if I recall, that is still open (#60) and I don't have Windows hardware, let alone a Windows server.

I followed the instruction, but on the step 3 to install the package locally, it said "option from() incorrectly specified". Can I get more information about how to figure out the correct path to the folder? Thanks!

**Comment by mcaceresb** [comment]
@annorazhao Where did you clone the repository?

**Comment by annorazhao** [comment]
> I think is this one from the first thread you posted: https://github.com/mcaceresb/stata-gtools

**Comment by mcaceresb** [comment]
@annorazhao I meant in your computer. You need to replace the path in `from()` with the path in your computer where `stata-gtools` was cloned into. So, where is it in your computer?

**Comment by annorazhao** [comment]
That is the place I got confused, in my laptop, the packages are installed under `/Users/.../Library/Application Support/Stata/ado/plus`, the ssc installed gtools are stored under the subfolder "g", how should I replace the path? Sorry that I'm a novice and know very few about this. Thanks for the help!

**Comment by mcaceresb** [comment]
> That is the place I got confused, in my laptop, the packages are installed under `/Users/.../Library/Application Support/Stata/ado/plus`, the ssc installed gtools are stored under the subfolder "g", how should I replace the path? Sorry that I'm a novice and know very few about this. Thanks for the help!

It seems the SSC version fails on newer OSX systems and you have to compile the plugins yourself. In order to do this, you need to follow  the steps [here](https://github.com/mcaceresb/stata-gtools/issues/87#issuecomment-1196870571). If you have a `gtools` installation under `/Users/.../Library/Application Support/Stata/ado/plus` then you have not done step 2.

- If you did step 1, then you should be able to type `pwd` into the the terminal. Copy the  output (a directory path will be printed).
- If you did step 2, then `gtools` should not be installed in your system. At this point, there shouldn't be any `gtools` files in `/Users/.../Library/Application Support/Stata/ado/plus/g`. Please check this is the case.
- For step 3, you need to copy the path you found in the first bullet and replace `path_to_folder_where_gtools_was_compiled` with that path. The final command will be something like `net install gtools, from(/Users/.../stata-gtools/build) replace`

**Comment by mcaceresb** [comment]
@austinsmoss I recently found [this article](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) on cross-compiling and it worked for another project. Can you re-install gtools from the `develop` branch (`gtools, upgrade branch(develop)`) and try it out?

**Comment by austinsmoss** [comment]
@mcaceresb I re-installed from the develop branch and it is working. Great solution!
